### ISSUE TITLE
Gerhard - wow, you really worked hard on this outstanding Hugo example app

### ISSUE THREAD

**Issue by longtimedeveloper** [gj52/HugoSample#1]
Gerhard,

Wanted to thank you for sharing your Hugo expertise.  You have encouraged me to start my own **Sandbox project** to play in.  

I've learned a lot from studying your work, sir!

I am retired as well.  I wrote my first program in 1972. 

Just started with Hugo to replace WordPress sites that I have written for customers.

Much respect and thank you again,

Karl

I hope the below translation is correct.  Apologies if it is off.
Ich hoffe die folgende Übersetzung ist korrekt. Entschuldigung, wenn es aus ist.

Gerhard,

Ich wollte mich bei Ihnen für das Teilen Ihres Hugo-Fachwissens bedanken. Sie haben mich ermutigt, mein eigenes ** Sandbox-Projekt ** zu starten, um darin zu spielen.

Ich habe viel gelernt, indem ich Ihre Arbeit studiert habe, Sir!

Ich bin auch im Ruhestand. Ich habe mein erstes Programm 1972 geschrieben.

Ich habe gerade mit Hugo angefangen, um WordPress-Sites zu ersetzen, die ich für Kunden geschrieben habe.

Viel Respekt und nochmals vielen Dank,

Karl

**Comment by gj52** [comment]
Gern, ich bin auch in Rente und mache das, um mein Gehirn weiter zu fordern.  ;-)
